### ISSUE TITLE
Which values are converted?

### ISSUE THREAD

**Issue by timkelty** [ben-eb/postcss-convert-values#1]
Can you share the use case for this plugin
Why convert px to pc?
And can you customize what it converts?

I stumbled here looking for a way to convert values with units to unitless, but then thought maybe this would be similar to https://github.com/Compass/compass/blob/d5df161d0df7edc686e576b22412f437dd0590cc/core/stylesheets/compass/typography/_units.scss, which was nice in my Sass days.

**Comment by ben-eb** [comment]
This module will convert a value only if there is a smaller representation of it. For example, `500ms` in CSS can also be represented as `.5s`. I think such "lossy" conversions like your example are outside the scope of this module, which is essentially there to normalize length/duration values.

The why is simple; because `1pc` is smaller than `16pc`, which when minifying will make a difference. https://github.com/ben-eb/cssnano

See the tests for more: https://github.com/ben-eb/postcss-convert-values/blob/master/test.js

**Comment by timkelty** [comment]
Thanks for the clarification!

**Comment by linmic** [comment]
Hi, I'm wondering if it should convert in to px depending on the dpi instead of converting px to in(I understand this is your micro optimisation)?
